In [1]:
a####hEADING 2
#####Heading 3
######hEADING 4


In [2]:
#ESC+M-->CONVERT TO MARKDOWN SHELL
#shift+enter-->
#ESC+A--> INSERT THE SHELL ABOVE THE CURRENT SHELL
#ESC+B-->INSERT THE SHELL BELOW THE CURRENT SHELL


In [4]:
import array
d1=array([45,74,85,36])
d1

TypeError: 'module' object is not callable

In [5]:
d1


NameError: name 'd1' is not defined

In [6]:
import time

start_time=time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]

op=list(map(lambda x,y:x*y,list1,list2))
end_time=time.time()

print("Time taken by list operation",end_time-start_time)

Time taken by list operation 0.015624761581420898


In [9]:
import time
import numpy as np

start_time1=time.time()

ar1=np.array(list1)
ar2=np.array(list2)

ar1*ar2

end_time1=time.time()

print("Time taken by arrays operation is : ",end_time1-start_time1)

Time taken by arrays operation is :  0.015619754791259766


In [11]:
d2=np.array([[23,34,56],[25,67,89]])
d2

array([[23, 34, 56],
       [25, 67, 89]])

In [12]:
d2[0]

array([23, 34, 56])

In [13]:
d2[1]

array([25, 67, 89])

In [14]:
d2[[0][1]]

IndexError: list index out of range

In [15]:
d2[0][1]

34

In [16]:
d2[2][1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [17]:
d2[1][2]

89

In [18]:
d2[1][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [19]:
d2[0][1]

34

In [20]:
d2[0][2]

56

In [21]:
d2[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [22]:
d2[0][2]

56

In [23]:
d2[1].max()

89

In [24]:
d2[:,2]

array([56, 89])

In [25]:
d2[1].min()

25

In [26]:
d2[0].min()

23

In [27]:
d2[0].sum()

113

In [28]:
d2[1].sum()

181

In [29]:
d2[0].avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [ ]:
d2[1].avg()

In [30]:
d2[1].sum()

181

In [31]:
d2[0].sum()

113

In [32]:
d2.sum(axis=0)
d2

array([ 48, 101, 145])

In [33]:
d2

array([[23, 34, 56],
       [25, 67, 89]])

In [34]:
d2.sum(axis=1)
d2

array([[23, 34, 56],
       [25, 67, 89]])

In [35]:
d2.sum(axis=1)

array([113, 181])

In [37]:
for i in range(1,11):
    print(i,end=".")

1.2.3.4.5.6.7.8.9.10.

In [42]:
for i in range(1,10,1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [41]:
range(1,10,2)

range(1, 10, 2)

In [45]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [46]:
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [48]:
print(np.ones([5,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
np.linalg.eig(mat)

NameError: name 'mat' is not defined

In [1]:
import numpy as np


In [2]:
np.sin(90)

0.8939966636005579

In [3]:
import numpy as np
np.sin(90)

0.8939966636005579

In [4]:
np.sinh(10)

11013.232874703393

In [5]:
np.arcsin(0)

0.0

In [6]:
np.arcsin(0.5)

0.5235987755982989

In [7]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array.max()

9

In [9]:
array.min()

1

In [10]:
array.argmax()

8

In [11]:
array.argmin()

0

sec1=np.array(np.random.randint(10,20,[4,4])))

In [13]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[15, 13, 10, 19],
       [10, 11, 16, 17],
       [10, 17, 13, 13],
       [19, 15, 18, 19]])

In [14]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[9, 6, 3, 8],
       [2, 5, 8, 3],
       [1, 3, 1, 7],
       [9, 2, 5, 9]])

In [15]:
np.vstack((sec1,sec2))

array([[15, 13, 10, 19],
       [10, 11, 16, 17],
       [10, 17, 13, 13],
       [19, 15, 18, 19],
       [ 9,  6,  3,  8],
       [ 2,  5,  8,  3],
       [ 1,  3,  1,  7],
       [ 9,  2,  5,  9]])

In [16]:
np.split(sec1,[2,2])

[array([[15, 13, 10, 19],
        [10, 11, 16, 17]]),
 array([], shape=(0, 4), dtype=int32),
 array([[10, 17, 13, 13],
        [19, 15, 18, 19]])]

In [17]:
np.vsplit(sec1,[2,2])

[array([[15, 13, 10, 19],
        [10, 11, 16, 17]]),
 array([], shape=(0, 4), dtype=int32),
 array([[10, 17, 13, 13],
        [19, 15, 18, 19]])]

In [18]:
np.hsplit(sec1,[2,2])

[array([[15, 13],
        [10, 11],
        [10, 17],
        [19, 15]]), array([], shape=(4, 0), dtype=int32), array([[10, 19],
        [16, 17],
        [13, 13],
        [18, 19]])]

In [19]:
np.abs(100.25)

100.25

In [20]:
np.round(100.25)

100.0

In [21]:
np.ceil(10.23)

11.0